version: '3.8'
services:
  nats:
    image: nats:latest
    ports:
      - '4222:4222'  # NATS client port
      - '6222:6222'  # Clustering port
      - '8222:8222'  # HTTP monitoring port
      - '9222:9222'  # WebSocket port
    command: >
      -js
      -ws
    volumes:
      - nats_data:/data

  recording_service:
    build: ./recording_service
    depends_on:
      - nats

  transcription_service:
    build: ./transcription_service
    depends_on:
      - nats

  summarization_service:
    build: ./summarization_service
    depends_on:
      - nats

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - nats

volumes:
  nats_data:
